# Generated by Django 3.0.5 on 2021-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
